# -*- coding: utf-8 -*-
"""FINAL CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UkDzTnR13QM7Q68CCsv48hP0Cv9Wfeg
"""

import json  # Imports the json module for JSON parsing.
from functools import reduce  # For merging DataFrames iteratively in the main function
from typing import Dict, List, Optional  # type hints for better code readability
import re  # Imports the regular expression module for text processing.
import pandas as pd  # for DataFrame creation and data manipulation.
import requests  # This library for making HTTP requests to the World Bank API.
from requests.exceptions import HTTPError, RequestException, Timeout, ConnectionError  # Imports specific exception classes for handling HTTP, request, timeout, and connection errors.
import time  # Imports the time module for adding delays during retry attempts for rate limiting.
INDICATORS = {  # Defines a dictionary mapping human-readable indicator names to World Bank API codes.
    "population": "SP.POP.TOTL",  # Maps "population" to the API code for total population.
    "growth_rate": "SP.POP.GROW",  # Maps "growth_rate" to the API code for population growth rate
    "area": "AG.LND.TOTL.K2",  # Maps "area" to the API code for total land area in square kilometers.
    "density": "EN.POP.DNST",  # Maps "density" to the API code for population density.
}  # Closes the INDICATORS dictionary definition.
API_TEMPLATE = ("https://api.worldbank.org/v2/country/all/indicator/{indicator}""?format=json&MRV=1&per_page=20000")# Begins a string template for the World Bank API endpoint URL. It specifies the base URL for fetching indicator data for all countries and adds query parameters for JSON format, most recent value, and 20,000 results per page.Closes the API_TEMPLATE string definition.
def fetch_indicator(indicator_code: str, session: Optional[requests.Session] = None) -> pd.DataFrame:  # Defines a function to fetch an indicator’s data, with type hints for input and output.Documents the function’s purpose: fetching the most recent data as a DataFrame.
    url = API_TEMPLATE.format(indicator=indicator_code)  # Formats the API URL by inserting the indicator code into the template.
    sess = session or requests.Session()  # Uses the provided session or creates a new one for HTTP requests.
    max_retries = 3  # Sets the maximum number of retry attempts for handling rate limit errors.
    retry_delay = 5  # Defines a 5-second delay between retry attempts.
    for attempt in range(max_retries):  # Starts a loop to attempt the API request up to max_retries times.
        try:  # Begins a try block to handle potential HTTP or request errors
            r = sess.get(url, timeout=30)  # Sends a GET request to the API with a 30-second timeout.
            r.raise_for_status()  # Raises an HTTPError if the response status code indicates an error
            payload = r.json()  # Parses the JSON response into a Python dictionary.
            # More robust validation of the API response structure
            if not isinstance(payload, list) or len(payload) < 2: # Checks if 'payload' is NOT a list OR if it has fewer than 2 elements.The API is expected to return a list with at least 2 items (metadata and actual data).
                print(f"API response for {indicator_code} is not in the expected list format.")# Prints an error message indicating that the API response format is not what was expected.
                return pd.DataFrame(columns=["country", "value"])# Returns an empty pandas DataFrame with "country" and "value" as column names.
            metadata = payload[0]# Assigns the first element of the payload list to 'metadata'.This contains information like total records, pagination, or other meta info.
            data = payload[1]# Assigns the second element of the payload list to 'data'.This usually contains the actual dataset (rows of values per country).
            if data is None:# Checks if the 'data' part of the response is None (meaning no actual data was returned).
                print(f"API response for {indicator_code} contains no data.")# Prints an error message indicating that no data is available for this indicator.
                return pd.DataFrame(columns=["country", "value"])# Returns an empty DataFrame to keep the output structure consistent.
            if not isinstance(data, list):# Checks if the 'data' portion is NOT a list (which it should be if the API is returning multiple rows).
                 print(f"API response data for {indicator_code} is not in the expected list format.")# Prints an error message indicating that the data structure was not as expected.
                 return pd.DataFrame(columns=["country", "value"])# Returns an empty DataFrame with the expected column names.
            rows = []  # Initializes an empty list to store parsed data rows.
            for rec in data:  # Loops through the data entries in the second element of the JSON payload.
                # More robust handling of missing keys in the data records
                country_info = rec.get("country", {})#Retrieves the value associated with the "country" key from the 'rec' dictionary.If "country" is not present, it returns an empty dictionary as a default.
                country_name = country_info.get("value")# Extracts the "value" key from the 'country_info' dictionary. This typically contains the full country name (e.g., "Canada", "Ghana").
                iso3_code = rec.get("countryiso3code")# Retrieves the value of "countryiso3code" from the 'rec' dictionary.This is usually the 3-letter ISO code for the country (e.g., "CAN", "GHA").
                value = rec.get("value")#Retrieves the value of "value" from the 'rec' dictionary.This usually contains the main numerical or textual data point for the indicator being processed.
                if country_name and iso3_code and value is not None:
                    rows.append({ "country": country_name, "iso3": iso3_code,"value": value,})#Begins appending a dictionary to the rows list for each data entry.Opens a dictionary for a single row of country data and extracts the country code from the nested country dictionary, safely handling missing keys. Extracts the ISO3 country code, allowing for None if missing and also extracts the indicator value, allowing for None if missing.Closes the dictionary for the row and the append call for the row.
                else:
                    # Optional: Log or print a warning for records with missing essential data
                    print(f"Skipping record with missing data for indicator {indicator_code}: {rec}")#Prints a message indicating that the current record (rec) is being skipped because it has missing or incomplete data for the given 'indicator_code'.The record's full content is displayed to help with debugging.
            df = pd.DataFrame(rows)# Creates a pandas DataFrame from the list of rows.
            if df.empty:#Checks if the DataFrame 'df' contains no rows (i.e., it's empty).This means no valid data was collected or processed.
                 print(f"No valid data records found for indicator {indicator_code}.")#Prints a message indicating that no usable data was found for this specific indicator.
                 return pd.DataFrame(columns=["country", "value"])#Returns a new empty DataFrame with the expected columns ("country" and "value") to maintain a consistent output format for downstream processing.
            df = df.drop_duplicates(subset=["iso3"]).reset_index(drop=True)# Removes duplicate rows based on ISO3 code and resets the index.
            return df# Returns the processed DataFrame with the indicator data.
        except Timeout:# Catches a Timeout exception, which occurs when the request takes too long to get a response from the API.
            if attempt < max_retries - 1:#Checks if the current attempt number is less than the maximum allowed retries minus 1. This means there are still retry attempts left.
                print(f"Request timed out for {indicator_code}. Retrying in {retry_delay} seconds...")# Prints a message showing which indicator failed due to timeout and how long the program will wait before retrying.
                time.sleep(retry_delay)#Pauses execution for 'retry_delay' seconds before retrying the request.
                continue#Skips the rest of the loop body and starts the next retry attempt.
            else:#If there are no retry attempts left:
                print(f"Max retries reached for {indicator_code} (timeout). Returning empty DataFrame.")#Prints a message indicating that the maximum retry limit has been reached for this indicator.
                return pd.DataFrame(columns=["country", "value"])#Returns an empty DataFrame with the expected columns to maintain consistent output.
        except ConnectionError:## Catches a ConnectionError, which occurs if there is a network issue or the API server cannot be reached.
             if attempt < max_retries - 1:#Checks if there are still retry attempts remaining.
                print(f"Connection error for {indicator_code}. Retrying in {retry_delay} seconds...")#Prints a message indicating a connection issue and the delay before the next retry.
                time.sleep(retry_delay)#Waits for the specified retry delay before retrying.
                continue#Moves to the next retry attempt.
             else:#If no retry attempts are left:
                print(f"Max retries reached for {indicator_code} (connection error). Returning empty DataFrame.")#Prints a message that the maximum retries have been reached for this indicator.
                return pd.DataFrame(columns=["country", "value"])#Returns an empty DataFrame with "country" and "value" columns for consistent output.
        except HTTPError as e:  # Catches HTTP errors raised by raise_for_status().
            if r.status_code == 429:  # Checks if the error is a 429 (Too Many Requests) status code for rate limiting.
                if attempt < max_retries - 1:  # Ensures there are retries left before proceeding.
                    print(f"Rate limit exceeded for {indicator_code}. Retrying in {retry_delay} seconds...")  # Prints a message indicating a retry attempt for rate limiting.
                    time.sleep(retry_delay)  # Pauses execution for the specified delay to respect rate limits.
                    continue  # Continues to the next loop iteration to retry the request.
                else:  # Handles the case where maximum retries are exhausted.
                    print(f"Max retries reached for {indicator_code} (status 429). Returning empty DataFrame.")  # Notifies that retries failed and an empty DataFrame will be returned.
                    return pd.DataFrame(columns=["country", "value"])  # Returns an empty DataFrame for failed 429 errors.
            else:  # Handles other HTTP errors (e.g., 404 for invalid endpoint).
                print(f"HTTP error for {indicator_code}: {r.status_code}. Returning empty DataFrame.")  # Notifies of the specific HTTP error and status code.
                return pd.DataFrame(columns=["country", "value"])  # Returns an empty DataFrame for other HTTP errors.
        except RequestException as e:  # Catches general request exceptions (e.g., network issues, timeouts).
            print(f"Request failed for {indicator_code}: {e}. Returning empty DataFrame.")  # Notifies of the request failure with the error message.
            return pd.DataFrame(columns=["country", "value"])  # Returns an empty DataFrame for request failures.
        except json.JSONDecodeError:# Handles the specific error that occurs if the JSON response is not valid or cannot be parsed
            print(f"Failed to decode JSON response for {indicator_code}. Returning empty DataFrame.")# Prints an error message indicating which indicator failed and that an empty DataFrame will be returned.
            return pd.DataFrame(columns=["country", "value"])# Returns an empty pandas DataFrame with predefined column names "country" and "value"
        except Exception as e:# Catches any other type of unexpected error that wasn't handled by the previous except block
            print(f"An unexpected error occurred for {indicator_code}: {e}. Returning empty DataFrame.")# Prints a generic error message with the indicator code and the actual exception message (e).
            return pd.DataFrame(columns=["country", "value"])# Returns an empty pandas DataFrame with the same predefined column names
def main(out_path: str, limit: Optional[
    int] = None):  # Defines the main function to orchestrate data fetching and saving, with optional row limit.
    session = requests.Session()  # Creates a session for reusing HTTP connections across requests.
    dfs: List[pd.DataFrame] = []  # Initializes an empty list to store DataFrames for each indicator.
    for field, code in INDICATORS.items():  # Iterates over the INDICATORS dictionary to fetch each indicator.
        print(f"Fetching {field} ({code}) ...")  # Prints a progress message for the current indicator being fetched.
        df = fetch_indicator(code, session=session)  # Calls fetch_indicator to retrieve data for the current indicator.
        if not df.empty: # Check if the fetched DataFrame is not empty before renaming and appending
            df = df.rename(columns={"value": field})  # Renames the "value" column to the indicator’s human-readable name.
            dfs.append(df)  # Appends the DataFrame to the list of DataFrames.
        else:
            print(f"Skipping merge for {field} due to empty DataFrame.")#Prints a message indicating that the merge operation for the specified 'field' is being skipped because the DataFrame involved is empty, preventing further processing.
    # Merge on iso3 + country
    if not dfs: # Check if the list of DataFrames is empty before attempting to reduce
        print("No DataFrames to merge. Exiting.")#Prints a message indicating that there are no DataFrames available for merging, so the merge operation cannot proceed.
        return#Exits the current function immediately, stopping further execution.
    combined = reduce(lambda left, right: pd.merge(left, right, on=["iso3", "country"], how="outer"), dfs,) # Begins merging all DataFrames using reduce.Defines a merge function to combine DataFrames on ISO3 and country with an outer join. Specifies the list of DataFrames to merge and closes the reduce call to create a combined DataFrame.
    # Reorder and (optionally) limit rows
    cols = ["country", "population", "growth_rate", "area", "density"]  # Defines the desired column order for the final output.
    # Ensure all columns in 'cols' are present in 'combined' before reordering.
    present_cols = [col for col in cols if col in combined.columns]# Keep iso3 temporarily if it exists in the DataFrame
    combined = combined[["country", "iso3"] + [col for col in present_cols if col not in ["country", "iso3"]]] if "iso3" in combined.columns else combined[[col for col in present_cols if col != "country"]]#Reorders 'combined' DataFrame columns:If 'iso3' exists, place "country" and "iso3" first, then other columns excluding those two;else, include all columns from 'present_cols' except "country".
    combined = combined.sort_values("country").reset_index(drop=True)  # Sorts the DataFrame by country and resets the index.
    if limit:  # Checks if a row limit is specified.
        combined = combined.head(limit)  # Limits the DataFrame to the specified number of rows.
    # Ensure all columns in 'cols' are present in 'combined' before final column selection
    final_cols = [col for col in cols if col in combined.columns]# Creates a list 'final_cols' containing only those columns from 'cols'that actually exist in the 'combined' DataFrame's columns.This filters out any columns listed in 'cols' that are not present in 'combined'.
    combined = combined[final_cols]  # Select the final columns that are present.
    combined = combined.dropna()# Drop rows with any missing values.
    if combined.empty:# Checks if the 'combined' DataFrame has no rows
        print("Combined DataFrame is empty after dropping rows with missing values. Exiting.")# Prints a message indicating that after removing rows with missing data,the DataFrame is empty and further processing will stop.
        return#Exits the current function immediately to prevent further execution on an empty DataFrame.
    combined.to_csv(out_path, index=False, encoding="utf-8")  # Saves the DataFrame to a CSV file without the index, using UTF-8 encoding.
    print(f"Saved {len(combined)} rows to {out_path}")  # Prints a confirmation message with the number of rows saved.
    print(f"File '{out_path}' created successfully.") # Add this line to confirm file creation
main(out_path="worldbank_country_stats.csv",limit=None)  # Calls the main function to run the script, saving output to worldbank_country_stats.csv with no row limit.
# Load the dataset from the uploaded file
file_path = "/content/worldbank_country_stats.csv"#Defines the file path to the input CSV file containing the World Bank country statistics dataset.
df_text = pd.read_csv(file_path) #Reads the CSV file located at file_path into a pandas DataFrame.The pd.read_csv function loads the CSV file into df_text, creating a DataFrame.
# Make a copy of the original dataset
df_cleaned = df_text.copy() #Creates a copy of the original DataFrame df_text to avoid modifying the original data during cleaning. The copy() method ensures that changes to df_cleaned do not affect df_text, preserving the raw data for reference or debugging.
# Function to clean country names
def clean_country_name(name): #Defines a function clean_country_name to standardize country names in the dataset.The function takes a single argument name (a country name) and applies a series of cleaning steps to remove inconsistencies, such as quotes, commas, or regional qualifiers.
    if not isinstance(name, str): #Checks if the input name is a string; if not, returns it unchanged.
        return name #This handles cases where the country name might be missing to avoid errors in string operations. Non-string values are returned as-is.
    name = re.sub(r'^"|"$', '', name.strip()) #The re.sub function uses the regular expression r'^"|"$ to match a double quote (") at the start (^) or end ($) of the string. The strip() method removes leading/ending whitespace before applying the regex.
    # Replace commas and periods with spaces, remove qualifiers
    name = re.sub(r'[,.](?:\s*(The|Rep\.|RB|Islamic Rep\.|Dem\. Rep\.|People\'s Rep\.|Fed\. Sts\.|US))?$', '', name)#Removes commas or periods followed by specific trailing qualifiers (e.g., "The", "Rep.", "US") from the country name.The regex [,.] matches a comma or period. The (?:\s*(The|Rep\.|...))?$ part matches optional qualifiers at the end of the string, with \s* allowing for zero or more spaces. The entire match is replaced with an empty string, effectively removing these patterns.
    # Replace remaining commas or periods with spaces
    name = re.sub(r'[,.]', ' ', name)#This code replaces any remaining commas or periods in the country name with a single space.This ensures that commas or periods within the name (not caught by the previous step) are converted to spaces for consistency.
    # Normalize multiple spaces
    name = re.sub(r'\s+', ' ', name).strip()#Replaces multiple consecutive spaces with a single space and removes leading/ending spaces.The regex \s+ matches one or more whitespace characters, replacing them with a single space. The strip() method ensures no extra spaces remain at the start or end.
    # Convert to title case
    name = name.title()#This code capitalizes the first letter of every country name. The title() method standardizes the case of the name, making it consistent.
    return name #Returns the cleaned country name which is stored in the DataFrame.
#Check for missing values
missing_values = df_cleaned.isnull().sum()#Checks for missing values in each column of the DataFrame.
if missing_values.any():#The any() method checks if any column has missing values. If True, it prints the missing_values Series; otherwise, it confirms no missing values.
    print("Missing values found:\n", missing_values)#Print if any missing is present in the DataFrame
else:
    print("No missing values found.")#Displays if no missing values are present in the DataFrame.
#Clean textual data (country names)
df_cleaned['country'] = df_cleaned['country'].apply(clean_country_name)#The apply method calls clean_country_name for each value in the country column, updating the column with cleaned names.
# Convert numerical columns with error handling
for col in ['population', 'growth_rate', 'area', 'density']:
    # Convert column to numeric, coercing errors to NaN
    df_cleaned[col] = pd.to_numeric(df_cleaned[col], errors='coerce')
    # Check if there are any NaN values after coercion
    if df_cleaned[col].isnull().any(): # Checks if there are any missing (NaN) values in the column 'col' of the DataFrame 'df_cleaned'.This often indicates that some non-numeric values were coerced to NaN during type conversion.
        print(f"Warning: Non-numeric values found and converted to NaN in column '{col}'.")#Prints a warning message to notify that non-numeric values were detected and replaced by NaN in this column.
df_cleaned.dropna(subset=['population', 'growth_rate', 'area', 'density'], inplace=True)# Drop rows with NaN values in numerical columns after conversion.
# Convert population and area to integer after dropping NaNs.
df_cleaned['population'] = df_cleaned['population'].astype(int)#Convert population to integer.
df_cleaned['area'] = df_cleaned['area'].round(0).astype(int)#Convert area to integet.
# Round growth_rate and density to 2 decimal places
df_cleaned['growth_rate'] = df_cleaned['growth_rate'].round(2)#Rounds the growth_rate and density columns to two decimal places.
df_cleaned['density'] = df_cleaned['density'].round(2)#Rounds the density columns to two decimal places. The round(2) method limits floating-point precision for readability and consistency, as growth rates and population densities are typically reported with limited decimals.
#Validate numerical ranges
# Check for negative or zero population/area
invalid_population = df_cleaned[df_cleaned['population'] <= 0]#Identifies rows with invalid population (less than or equal to zero).Boolean indexing (df_cleaned['population'] <= 0) filters rows where population or area is non-positive, storing results in invalid_population and invalid_area.
invalid_area = df_cleaned[df_cleaned['area'] <= 0]##Identifies rows with invalid area values (less than or equal to zero).Boolean indexing (df_cleaned['area'] <= 0) filters rows where area is non-positive, storing results in invalid_population and invalid_area.
if not invalid_population.empty:#Prints any rows with invalid population values.
    print("Invalid population values:\n", invalid_population)#The empty attribute checks if the filtered DataFrames are non-empty. If invalid values exist, they are printed for review; otherwise, nothing is printed.
if not invalid_area.empty:#Prints any rows with invalid area values
    print("Invalid area values:\n", invalid_area)#The empty attribute checks if the filtered DataFrames are non-empty. If invalid values exist, they are printed for review; otherwise, nothing is printed.
#Flag regional aggregates important for NLP filtering)
regional_terms = ['World', 'Africa', 'Asia', 'Europe', 'America', 'Caribbean', 'OECD', 'IDA', 'IBRD', 'income', 'dividend', 'Small states', 'Union', 'Area']#Defines a list of terms that indicate regional or aggregate entities rather than individual countries.These terms (e.g., "World", "Africa") are used to identify rows that represent regions or groups, which may need special handling in downstream NLP tasks.
df_cleaned['is_region'] = df_cleaned['country'].str.contains('|'.join(regional_terms), case=False, na=False).astype(int)#Creates a new column is_region to flag rows where the country name contains regional terms.The str.contains method checks if any term in regional_terms (joined with | for regex OR) appears in the country column, ignoring case (case=False) and handling missing values (na=False). The result is converted to 1 (True) or 0 (False) using astype(int).
#Save cleaned dataset to CSV
cleaned_csv = df_cleaned.to_csv(index=False)#Converts the cleaned DataFrame to a CSV file. The to_csv(index=False) method generates a CSV representation of df_cleaned without including the DataFrame index, storing it in cleaned_csv as a file.
try:
    with open('cleaned_worldbank_country_stats.csv', 'w', encoding='utf-8') as f:#Writes the CSV string to a new file named cleaned_worldbank_country_stats.csv.The with open context manager opens the file in write mode ('w').
        f.write(cleaned_csv)#f.write saves the CSV file to disk.
    print("Cleaned data saved to 'cleaned_worldbank_country_stats.csv'")#Prints a confirmation message indicating that the cleaned DataFrame has been successfully saved to a CSV file.
except IOError as e:#Catches input/output errors that may occur during the file-saving process, such as permission issues, disk errors, or file access problems.
    print(f"Error saving cleaned data to CSV: {e}")#Prints an error message showing details of the IOError encountered while trying to save the CSV file.
# Preview cleaned data
display("\nCleaned Data Preview:\n", df_cleaned.head(10))#Displays the first 10 rows of the cleaned DataFrame for inspection.
#Code for NLP analysis
import nltk #Imports the nltk (Natural Language Toolkit) library for NLP tasks.Provides functions like word_tokenize and pos_tag used for linguistic analysis of country names.
from nltk.tokenize import word_tokenize #Imports the word_tokenize function from NLTK for splitting text into words.It is used in n the preprocess_text function to tokenize country names.
from nltk import FreqDist, pos_tag #Imports FreqDist for frequency distribution analysis and pos_tag for part-of-speech tagging.FreqDist is used to count word and POS tag frequencies, while pos_tag assigns grammatical categories to tokens.
from nltk.util import ngrams #Imports the ngrams function to generate sequences of words (bigrams and trigrams). Used to analyze multi-word patterns in country names.
from collections import Counter #Imports the Counter class for counting occurrences of items (e.g., n-grams), which is used to Used to compute the most common bigrams and trigrams.
import numpy as np #Imports the numpy library for numerical operations.it is used indirectly via scipy.stats for correlation calculations and to handle NaN values.
from scipy.stats import pearsonr #Imports the pearsonr function to calculate Pearson correlation coefficients for testing correlations between population density and growth rate, and between area and density.
import re #It imports the re module for regular expression operations for preprocess_text function to remove punctuation from country names.
# Download required NLTK data
try:
    nltk.download('punkt', quiet=True) #Downloads the punkt tokenizer models for word tokenization required for word_tokenize to function correctly.
    nltk.download('averaged_perceptron_tagger', quiet=True) #Downloads the averaged_perceptron_tagger model for POS tagging assign grammatical categories to tokens.
    nltk.download('punkt_tab', quiet=True) # Download the missing resources
    nltk.download('averaged_perceptron_tagger_eng', quiet=True) # Download the missing English POS tagger.
    print("NLTK data downloaded successfully.")#Prints a message confirming that the NLTK data has been downloaded without issues.
except Exception as e:#Catches any unexpected errors that occur during the NLTK data download process.
    print(f"Error downloading NLTK data: {e}")#Prints an error message with details about the exception encountered during the download.
# Load the dataset
try:
    data = pd.read_csv('/content/cleaned_worldbank_country_stats.csv')#Loads the cleaned World Bank dataset from a CSV file into a pandas DataFrame. The dataset contains columns like country, population, growth_rate, density, area, and is_region
    print("Cleaned data loaded successfully.")#Displays cleaned successfully loaded.
except FileNotFoundError:# Catches the specific error that occurs if the file 'cleaned_worldbank_country_stats.csv' does not exist or cannot be found at the specified path.
    print("Error: cleaned_worldbank_country_stats.csv not found.")#Displays if error is found.
    data = pd.DataFrame()#Exit or handle the error appropriately, e.g., set data to an empty DataFrame
if not data.empty: # Check if data is loaded and not empty before proceeding with analysis
    # Function to clean and tokenize country names
    def preprocess_text(text):#Defines a function to clean and tokenize text (country names) for NLP analysis.Prepares text by removing punctuation, converting to lowercase, and tokenizing.
        if not isinstance(text, str):  # Check if the input is a string.
            return []  # Return an empty list if not a string.
        # Remove punctuation and convert to lowercase
        text = re.sub(r'[^\w\s]', ' ', text.lower())#matches non-word, non-space characters, replacing them with spaces. lower() ensures consistency.
        tokens = word_tokenize(text)#Tokenizes the cleaned text into words using NLTK’s word_tokenize. Splits the text into a list of tokens (words).
        return tokens#Returns the list of tokenized output for further analysis.
    # Prepare text data
    country_names = data['country'].tolist()#Extracts the country column as a list of country names for linguistics analysis of country names.
    all_tokens = []#Initializes an empty list to store all tokens from country names for frequency analysis.
    for name in country_names:#Tokenizes each country name and adds the tokens to all_tokens and loops through country names, processes them, and extends the token list.
        processed_name = preprocess_text(name)## Calls the function 'preprocess_text' on the variable 'name' to clean or tokenize the text,returning a processed list of tokens or cleaned string assigned to 'processed_name'.
        all_tokens.extend(processed_name)## Adds the elements of 'processed_name' to the 'all_tokens' list, effectively accumulating all tokens from processed names into one list.
    # Word frequency analysis
    freq_dist = FreqDist(all_tokens)#Creates a frequency distribution of all tokens. This counts how often each word appears across all country names.
    common_words = freq_dist.most_common(10)#Extracsts the 10 most common words from the frequency distribution and stores the top words for linguistic analysis output.
    # N-gram analysis (bigrams and trigrams)
    bigrams = []#Initializes empty lists to store bigrams (2-word sequences)
    trigrams = []#Initializes empty lists to store trigrams (3-word sequences).
    for name in country_names:#Generates bigrams and trigrams for each country name with tokens which checks for non-empty token lists to avoid errors, then uses ngrams to create sequences.
        tokens = preprocess_text(name)## Applies the 'preprocess_text' function to the variable 'name' to clean and tokenize the text,and stores the resulting list of tokens (words) in the variable 'tokens'.
        if tokens: # Only generate ngrams if there are tokens
            bigrams.extend(ngrams(tokens, 2))#Generates all 2-word sequences (bigrams) from the list 'tokens' using the 'ngrams' function, then adds these bigrams to the 'bigrams' list, accumulating all bigram pairs.
            trigrams.extend(ngrams(tokens, 3))#Generates all 2-word sequences (bigrams) from the list 'tokens' using the 'ngrams' function, then adds these bigrams to the 'bigrams' list, accumulating all bigram pairs.
    bigram_freq = Counter(bigrams).most_common(10)#Counts the frequency of bigrams extracting the top 10.
    trigram_freq = Counter(trigrams).most_common(10)#Counts the frequency of trigrams, extracting the top 10.
    # Lexicographical analysis (POS tagging)
    pos_tags = []#Initializes an empty list to store POS-tagged tokens which collects tags for grammatical analysis.
    pos_tagging_skipped = False#Initializes a flag to track if POS tagging is skipped due to errors which is used to note errors in the output DataFrame.
    skipped_countries_pos = [] # To store names of countries skipped during POS tagging
    for name in country_names:#Performs POS tagging on tokens and handles potential errors. Tags tokens with grammatical categories, catching exceptions to avoid crashes. Sets pos_tagging_skipped to True if an error occurs.
        tokens = preprocess_text(name)## Processes the string 'name' through the 'preprocess_text' function, which typically cleans and tokenizes the text, returning a list of tokens stored in 'tokens'.
        if tokens: # Only perform POS tagging if there are tokens
            try:# Starts a try block to catch any exceptions that might occur during POS tagging.
                tagged_tokens = pos_tag(tokens)# Applies part-of-speech (POS) tagging to the list of tokens, assigning a POS tag (like noun, verb, adjective) to each token.The result is a list of (token, tag) tuples stored in 'tagged_tokens'.
                pos_tags.extend(tagged_tokens)# Adds the tagged tokens to the 'pos_tags' list, accumulating all POS-tagged tokens.
            except Exception as e: # Catching a broader exception to be safe
                print(f"Skipping POS tagging for '{name}' (tokens: {tokens}) due to error: {e}")# Prints a message indicating that POS tagging for the current 'name' (with its tokens) was skipped because an error 'e' occurred during the tagging process.
                pos_tagging_skipped = True# Sets a flag variable to True indicating that POS tagging was skipped for at least one entry.
                skipped_countries_pos.append(name)#Adds the current 'name' to a list called 'skipped_countries_pos' to keep track of all names for which POS tagging failed or was skipped.
    pos_freq = Counter(tag for word, tag in pos_tags) if pos_tags else Counter()#Counts the frequency of POS tags, defaulting to an empty Counter if no tags exist. Extracts tags from pos_tags tuples and counts their occurrences.
    # Filter countries (is_region == 0) for cleaner analysis
    countries_only = data[data['is_region'] == 0].copy() # Filters the DataFrame to include only non-regional entities (is_region == 0) and uses .copy() to avoid warnings when modifying the filtered DataFrame.
    if not countries_only.empty: # Check if countries_only is empty before proceeding with hypothesis testing
        # Hypothesis 1: Correlation between population density and growth rate
        # Ensure both columns are numeric and handle potential non-numeric values
        countries_only['density'] = pd.to_numeric(countries_only['density'], errors='coerce')#Converts density columns to numeric types, coercing invalid values to NaN.
        countries_only['growth_rate'] = pd.to_numeric(countries_only['growth_rate'], errors='coerce')#Converts growth_rate columns to numeric types, coercing invalid values to NaN.
        # Drop rows with NaN values after coercion for correlation calculation
        countries_only_cleaned = countries_only.dropna(subset=['density', 'growth_rate'])#Removes rows with NaN in density or growth_rate for correlation analysis.
        if not countries_only_cleaned.empty:# Checks if the DataFrame 'countries_only_cleaned' is not empty meaning it contains data to analyze.
            density_growth_corr, density_growth_p = pearsonr(countries_only_cleaned['density'], countries_only_cleaned['growth_rate'])#Calculates the Pearson correlation coefficient and p-value between the 'density' and 'growth_rate' columns in 'countries_only_cleaned' using the 'pearsonr' function from scipy.stats, 'density_growth_corr' stores the correlation coefficient,and 'density_growth_p' stores the significance p-value.
            hyp1_narrative = f"Hypothesis 1: The correlation between population density and growth rate is {density_growth_corr:.3f} (p-value: {density_growth_p:.3f}). "#Calculates the Pearson correlation and p-value between density and growth_rate if data is available and tests Hypothesis 1 on the relationship between these variables.
            if abs(density_growth_corr) < 0.3:# Checks if the absolute value of the correlation coefficient 'density_growth_corr' is less than 0.3,which typically indicates a weak or negligible linear relationship between the two variables.
                hyp1_narrative += "This weak correlation suggests that high-density countries like 'Malta' (density: 1659.73, growth: 3.83%) and low-density countries like 'Niger' (density: 19.98, growth: 3.28%) show varied growth rates."#Creates a narrative string summarizing the correlation result. The results are formatted to 3dp.
            else:
                hyp1_narrative += f"{'High' if density_growth_corr > 0 else 'Low'} density countries tend to have {'higher' if density_growth_corr > 0 else 'lower'} growth rates."# Updates the string variable 'hyp1_narrative' by appending a sentence describing the relationship between population density and growth rates. It inserts High" or "Low" based on whether the correlation 'density_growth_corr' is positive or negative,and similarly uses "higher" or "lower" to describe growth rates accordingly.
        else:
            hyp1_narrative = "Hypothesis 1: Could not calculate correlation between population density and growth rate due to insufficient valid data."
        # Hypothesis 2: Variability in growth rates for small vs. large populations
        # Ensure population column is numeric before filtering
        countries_only_cleaned['population'] = pd.to_numeric(countries_only_cleaned['population'], errors='coerce')#Converts the 'population' column in the 'countries_only_cleaned' DataFrame to numeric values. Any values that cannot be converted (e.g., invalid strings) are replaced with NaN due to 'errors="coerce"'.
        small_pop = countries_only_cleaned[countries_only_cleaned['population'] < 1000000].copy()#Filters countries into small (<1M)
        large_pop = countries_only_cleaned[countries_only_cleaned['population'] > 100000000].copy()#Filters countries into large (>100M) population groups.
        small_pop['growth_rate'] = pd.to_numeric(small_pop['growth_rate'], errors='coerce')#Ensures growth_rate is numeric in both filtered DataFrames.Redundant since growth_rate was already coerced in countries_only, but ensures robustness.
        large_pop['growth_rate'] = pd.to_numeric(large_pop['growth_rate'], errors='coerce')#Ensures growth_rate is numeric in both filtered DataFrames.Redundant since growth_rate was already coerced in countries_only, but ensures robustness.

        small_var = small_pop['growth_rate'].var() if not small_pop.empty else float('nan')#Calculates the variance of growth_rate for small population countries.Returns NaN if the DataFrames are empty to avoid errors.
        large_var = large_pop['growth_rate'].var() if not large_pop.empty else float('nan')#Calculates the variance of growth_rate for small population countries.Returns NaN if the DataFrames are empty to avoid errors.

        # Check if variances are not NaN before forming the narrative
        if not np.isnan(small_var) and not np.isnan(large_var):
            hyp2_narrative = f"Hypothesis 2: Small-population countries (e.g., 'Tuvalu': population 9646, growth -1.75%) have a growth rate variance of {small_var:.3f}, compared to {large_var:.3f} for large-population countries (e.g., 'India': population 1.45B, growth 0.89%). "
            hyp2_narrative += "Higher variance in small populations indicates more variable growth rates."
        else:
            hyp2_narrative = "Hypothesis 2: Could not calculate variance for small or large population growth rates due to insufficient valid data."
        # Hypothesis 3: Negative growth rates and regional patterns
        negative_growth = countries_only_cleaned[countries_only_cleaned['growth_rate'] < 0].copy()#Filters countries with negative growth rates which identifies countries for regional pattern analysis.
        negative_countries = negative_growth['country'].tolist()#Extracts country names with negative growth rates for linguistic analysis of these countries.
        if negative_countries:
            negative_tokens = [token for name in negative_countries for token in preprocess_text(name)]#Tokenizes country names with negative growth rates for for frequency analysis.
            negative_freq = FreqDist(negative_tokens).most_common(5)#Finds the five most common tokens in negative growth countries for analysis. It identifies common terms for Hypothesis 3.
            hyp3_narrative = f"Hypothesis 3: Countries with negative growth rates include {', '.join(negative_countries[:3])}. "#Creates a narrative for Hypothesis 3, summarizing negative growth countries and their common terms.
            hyp3_narrative += f"Common terms in these names: {negative_freq}. Many are associated with Europe (e.g., 'Albania,' 'Moldova'), suggesting a regional pattern."
        else:
            hyp3_narrative = "Hypothesis 3: No countries with negative growth rates found in the cleaned data."
        # Hypothesis 4: Relationship between land area and population density
        # Ensure area column is numeric
        countries_only_cleaned_area_density = countries_only_cleaned.dropna(subset=['area', 'density'])#Removes rows with NaN in area or density for correlation analysis.
        #Tests the correlation between area and density, creating a narrative.
        if not countries_only_cleaned_area_density.empty:
            area_density_corr, area_density_p = pearsonr(countries_only_cleaned_area_density['area'], countries_only_cleaned_area_density['density'])# Calculates the Pearson correlation coefficient and p-value between the 'area' and 'density' columns in the DataFrame 'countries_only_cleaned_area_density' using the 'pearsonr' function.'area_density_corr' stores the correlation coefficient indicating the strength and direction of the relationship, while 'area_density_p' stores the p-value indicating the statistical significance of the correlation.
            hyp4_narrative = f"Hypothesis 4: The correlation between land area and population density is {area_density_corr:.3f} (p-value: {area_density_p:.3f}). "
            hyp4_narrative += "Regions like 'South Asia' (density: 492.38, area: 3.35M km²) have high density despite moderate area, while 'Sub-Saharan Africa' (density: 51.45, area: 23.89M km²) has low density with large area." # Note: Example countries/regions in the narrative might not directly match the correlation result.
        else:
             hyp4_narrative = "Hypothesis 4: Could not calculate correlation between land area and population density due to insufficient valid data."
        # Hypothesis 5: Characteristics of high-growth countries
        high_growth = countries_only_cleaned[countries_only_cleaned['growth_rate'] > 3].copy()#Filters countries with growth rates above 3% to identify high-growth countries for analysis.
        high_growth_countries = high_growth['country'].tolist()#Extracts names of high-growth countries for the Hypothesis 5 narrative.
        high_growth_stats = high_growth[['population', 'density']].describe()#Computes descriptive statistics for population and density of high-growth countries. Provides mean, std, etc., for Hypothesis 5.
        if not high_growth_stats.empty:#Checking with the high_growth_stats is empty or not.
            # Ensure mean population and density are not NaN before formatting
            mean_population = high_growth_stats['population'].get('mean')# Retrieves the mean (average) value of the 'population' statistic from the 'high_growth_stats' dictionary.
            mean_density = high_growth_stats['density'].get('mean')# Retrieves the mean (average) value of the 'density' statistic from the 'high_growth_stats' dictionary.
            hyp5_narrative = f"Hypothesis 5: High-growth countries (>3% growth rate) include {', '.join(high_growth_countries[:3])}. "#Creates a narrative for Hypothesis 5, summarizing high-growth countries’ characteristics.Uses statistics to describe population and density trends.
            if not pd.isna(mean_population) and not pd.isna(mean_density):
                 hyp5_narrative += f"These countries have a mean population of {mean_population:.0f} and mean density of {mean_density:.2f}, suggesting moderate population sizes and densities."
            else:
                 hyp5_narrative += "Could not calculate mean population and density due to missing data in high-growth countries."
        else:
            hyp5_narrative = "Hypothesis 5: No high-growth countries found in the cleaned data."
    else: # countries_only is empty
        hyp1_narrative = "Hypothesis 1: Could not perform analysis as no non-regional countries were found."
        hyp2_narrative = "Hypothesis 2: Could not perform analysis as no non-regional countries were found."
        hyp3_narrative = "Hypothesis 3: Could not perform analysis as no non-regional countries were found."
        hyp4_narrative = "Hypothesis 4: Could not perform analysis as no non-regional countries were found."
        hyp5_narrative = "Hypothesis 5: Could not perform analysis as no non-regional countries were found."
    # Add 'Type' column to linguistic results
    linguistic_results = pd.DataFrame({#Initializes a pandas DataFrame named linguistic_results to store the results of linguistic analyses performed on the country column of the dataset.
        'Type': ['Linguistic'] * (4 if not pos_tagging_skipped else 3),#Defines the Type column of the linguistic_results DataFrame, labeling each row as a “Linguistic” analysis to distinguish it from hypothesis-related results.
        'Analysis': [#Defines the Analysis column, listing the specific types of linguistic analyses performed (e.g., word frequency, bigrams, trigrams, and optionally POS tag frequency).
            'Word Frequency','Bigram Frequency','Trigram Frequency'] + (['POS Tag Frequency'] if not pos_tagging_skipped else []),
        'Result': [str(common_words), str(bigram_freq),str(trigram_freq)] + ([str(pos_freq.most_common())] if not pos_tagging_skipped else []),#Defines the Result column, containing the actual outputs of the linguistic analyses.
        'Notes': ['', '', ''] + ([''] if not pos_tagging_skipped else ['POS tagging was skipped due to errors.']) })#Defines the Notes column, providing metadata or comments about each linguistic analysis, particularly to flag POS tagging errors.
    #Rename and align hypothesis results
    hypothesis_results = pd.DataFrame({#Initializes a pandas DataFrame named hypothesis_results to store the results of the five hypothesis tests, aligning its structure with linguistic_results for concatenation.
        'Type': ['Hypothesis'] * 5,#Defines the Type column, labeling each row as a “Hypothesis” result to distinguish it from linguistic results.
        'Analysis': [f'Hypothesis {i}' for i in range(1, 6)],#Defines the Analysis column, listing labels for the five hypotheses (e.g., “Hypothesis 1” through “Hypothesis 5”).
        'Result': [#Defines the Result column, containing the textual narratives for each hypothesis test.
            hyp1_narrative,
            hyp2_narrative,
            hyp3_narrative,
            hyp4_narrative,
            hyp5_narrative  ],
        'Notes': [''] * 5})# Add empty Notes column to match structure.
    combined_results = pd.concat([linguistic_results, hypothesis_results], ignore_index=True)# Combine them with aligned columns.
    # Save to CSV
    try:
        combined_results.to_csv('nlp_analysis_results.csv', index=False)# Save the combined results to a CSV file (without row indices)
        print("NLP analysis results saved to 'nlp_analysis_results.csv'")#Displays results in CSV file.
    except IOError as e:#Catches input/output errors that may occur during the file-saving process such as permission issues, disk errors, or file access problems.
        print(f"Error saving NLP analysis results to CSV: {e}")#Prints an error message showing details of the IOError encountered while trying to save the NLP results to a CSV file.
    # Display DataFrames
    display("Linguistic Analysis Results:", linguistic_results)# Display the Linguistic Analysis testing results in the console or notebook
    display("Hypothesis Testing Results:", hypothesis_results)# Display the Hypothesis testing results in the console or notebook
else:
    print("Skipping NLP analysis and hypothesis testing due to empty data.")#Displays if no data is available.